version: "3"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data      # mount folder data vào container (nếu cần)
    networks:
      - malware-net

networks:
  malware-net:
    driver: bridge
